"""Generate stimulus and expected results for sim/tb_top.sv."""

from __future__ import annotations

import argparse
import random
from pathlib import Path
from typing import List, Tuple

from . import protocol
from .bridge import DEFAULT_PRODUCTS
from .feeds import synthetic_trade_stream


def build_stream(n_trades: int, seed: int) -> Tuple[bytes, List[protocol.TradeMsg], protocol.Decoder]:
    products = DEFAULT_PRODUCTS.split(",")
    symbol_ids = {p: i for i, p in enumerate(products)}
    trades = synthetic_trade_stream(products, seed)
    rng = random.Random(seed)

    out = bytearray(b"\x00\x13\x37\xff")
    seq = 0
    out += protocol.encode_heartbeat(seq)
    seq += 1

    corrupt_index = n_trades // 2
    for i in range(n_trades):
        trade = next(trades)
        msg = protocol.make_trade_msg(symbol_ids[trade.product], trade.side, trade.price, trade.size)
        frame = protocol.encode_trade(seq, msg)
        seq += 1
        if i == corrupt_index:
            frame = frame[:-1] + bytes([frame[-1] ^ 0xFF])
        out += frame
        if i % 5 == 4:
            out.append(rng.randrange(0, protocol.SYNC[0]))  # never a sync byte

    decoder = protocol.Decoder()
    expected = [
        protocol.decode_trade(f.payload) for f in decoder.feed(bytes(out)) if f.msg_type == protocol.MSG_TRADE
    ]
    assert len(expected) == n_trades - 1
    return bytes(out), expected, decoder


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--trades", type=int, default=16)
    parser.add_argument("--seed", type=int, default=7)
    args = parser.parse_args()

    stream, expected, decoder = build_stream(args.trades, args.seed)
    args.out.mkdir(parents=True, exist_ok=True)

    (args.out / "stream.hex").write_text("".join(f"{b:02x}\n" for b in stream))
    (args.out / "trades.hex").write_text(
        "".join(f"{t.symbol_id:02x}{t.side:02x}{t.price:08x}{t.qty:08x}\n" for t in expected)
    )
    errors = decoder.checksum_errors + decoder.length_errors + decoder.seq_gaps
    (args.out / "vectors.svh").write_text(
        "// Generated by host/gen_vectors.py -- do not edit.\n"
        f'`define STREAM_HEX "{args.out / "stream.hex"}"\n'
        f'`define TRADES_HEX "{args.out / "trades.hex"}"\n'
        f"`define N_BYTES {len(stream)}\n"
        f"`define N_TRADES {len(expected)}\n"
        f"`define N_CHECKSUM_ERRORS {decoder.checksum_errors}\n"
        f"`define N_SEQ_GAPS {decoder.seq_gaps}\n"
        f"`define N_ERRORS {errors}\n"
    )
    print(f"wrote {len(stream)} bytes, {len(expected)} trades, {errors} expected errors to {args.out}")


if __name__ == "__main__":
    main()
